### PR TITLE
[Feature #159586213] Create home page 

### PR DESCRIPTION
**Pull request by mmosoroohh**
#### What does this PR do?
Have completed the frontend design for the home page.

#### Description of tasks to be completed
It's a landing page for the web application with a brief description of what the web application is all about.

#### How should this be manually tested?
- Clone or download the repository.
- Navigate to the UI directory and open the index.hmtl file on a browser to access it.

#### Any background context you want to provide?
- CSS Stylesheet in css folder
- Image in img folder 

#### What are the relevant Pivotal Tracker Stories?
[#159586213](https://www.pivotaltracker.com/story/show/159586213)

#### Screenshot (If appropriate)
screenshot from 2018-08-08 21-32-36

### CODE REVIEW

**Comment by Gidraf** [comment]
It's great but perhaps consider changing the font color to something darker

**Comment by mmosoroohh** [comment]
Thank you @Gidraf 
Ill try to do that to see it turns out.

**Comment by Kimaiyo077** [comment]
It looks great... i like the simplicity

**Comment by mmosoroohh** [comment]
Thank you @Kimaiyo077

**Pull request closed without merging**
