### PR TITLE
[Feature #159718588] Testing endpoints API 

### PR DESCRIPTION
**Pull request by mmosoroohh**
#### What does this PR do?
Creation of endpoints, test driven developments for endpoints of the API

#### Description of Task to be completed?
Creation of Test driven development for the endpoints and working endpoints:
<pre>
<table>
<tr><th>Test</th>
<th>API-endpoint</th>
<th>HTTP-Verbs</th>
</tr>
<tr>
<td>User can post a questiont</td>
<td>/api/v1/questions</td>
<td>POST</td>
</tr>
<tr>
<td>User can view all questions</td>
<td>/api/v1/questions</td>
<td>GET</td>
</tr>
</tr>
</tr>
</table>
</pre>

#### How should this manually be tested?
- Navigate to the StackOverflow-lite repository.
- Clone or download the repository
<pre>
<code>
$ . venv/bin/activate
$ pip install -r requirements.txt
$ python run.py
</code>
</pre>

### Any background context you want to provide?
Data structures

#### What are the relevant Pivotal tracker stories?
[#159718588](https://www.pivotaltracker.com/story/show/159718588)
[#159718573](https://www.pivotaltracker.com/story/show/159718573)
[#159718595](https://www.pivotaltracker.com/story/show/159718595)
[#159718595](https://www.pivotaltracker.com/story/show/159718595)

screenshot (If appropriate)
screenshot from 2018-08-13 12-29-05

screenshot from 2018-08-13 12-30-45

### CODE REVIEW

**Comment by TheSteelGuy** [comment]
All seems awesome a part from what i left on my reviews. and also i guess it is always good to have single feature for a PR for example your PR heading reads **[Feature #159718588] Testing endpoints API**  then you have given several stories at the bottom ie

- #159718588
- #159718573
- #159718595
- #159718595

 So i think either you include all the stories in the head or none if you want to address several stories on a single PR

**Comment by Tony-Ndichu** [comment]
Hey, nice job, is that postman you're testing with?

**Comment by mmosoroohh** [comment]
@TheSteelGuy yeah you can do several stories I think if am not wrong 
@Tony-Ndichu yeah you test your endpoint functionality using postman

**Comment by TheSteelGuy** [comment]
That is awesome then

**Pull request merged**
